In [1]:
import numpy as np 
import pandas as pd

In [28]:
def sow(temperature, humidity, altitude, rain, sunshine):
  """
  Args:
    temperature(float): temperature measure in degrees centigrades.
    humidity(float): relative humidity in the air.
    altitude(float): masl of the place to sow.
    rain(float): milimeters of rain in a squared meter in a month.
    sunshine(float): hours of sun in a day.

  Output:
  sow(int): 1 if is good to sow, 0 otherwise.
  """
  sow = None
  if (19 <= temperature <= 22 and 0.5 <= humidity <= 0.8 and 800 <= altitude <= 2100 and 120 <= rain <= 180 and 4.5 <= sunshine <= 5.5):
    sow = 1
  else:
    sow = 0
  return sow

In [18]:
temperature = np.round(np.random.normal(20, 2.5, 10000), 2)
humidity = np.round(np.random.normal(0.6, 0.08, 10000), 4)
altitude = np.round(np.random.normal(1500, 100, 10000), 2)
rain = np.round(np.random.normal(150, 10, 10000), 2)
sunshine = np.round(np.random.normal(5.0, 0.1, 10000), 2)

In [29]:
to_sow = np.array([sow(temperature[i], humidity[i], altitude[i], rain[i], sunshine[i]) for i in range(10000)])
dictionary = {
    'temperature': temperature, 
    'humidity': humidity, 
    'altitude': altitude, 
    'rain': rain, 
    'sunshine': sunshine, 
    'sow': to_sow
    }
df = pd.DataFrame(dictionary)

In [20]:
df

      temperature  humidity  altitude    rain  sunshine  sow
0           20.56    0.5616   1792.51  157.98      5.00    1
1           19.89    0.4404   1491.87  138.53      5.18    0
2           19.13    0.6483   1442.02  135.11      4.93    1
3           18.18    0.6214   1508.78  158.78      5.08    0
4           23.06    0.6410   1595.61  161.61      4.88    0
...           ...       ...       ...     ...       ...  ...
9995        20.37    0.5752   1485.12  155.21      4.98    1
9996        20.29    0.5973   1397.37  143.33      5.06    1
9997        19.28    0.7241   1591.44  163.55      5.04    1
9998        22.12    0.5620   1302.65  133.17      5.03    0
9999        20.33    0.5113   1438.55  146.41      4.91    1

[10000 rows x 6 columns]

In [30]:
df.describe()

        temperature      humidity  ...      sunshine           sow
count  10000.000000  10000.000000  ...  10000.000000  10000.000000
mean      20.031190      0.600133  ...      5.002200      0.392700
std        2.511048      0.079884  ...      0.100253      0.488375
min       10.650000      0.304500  ...      4.620000      0.000000
25%       18.320000      0.547100  ...      4.940000      0.000000
50%       20.000000      0.601800  ...      5.000000      0.000000
75%       21.720000      0.652625  ...      5.070000      1.000000
max       29.620000      0.905900  ...      5.390000      1.000000

[8 rows x 6 columns]

In [32]:
from google.colab import drive
drive.mount('/gdrive')
df.to_csv('/gdrive/My Drive/coffee_sow/coffee_sow.csv', header=True)

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).